[[tasks]]

puzzle = '''
3x3;
 , , , , , , , , ,
 , ,7, , , ,2, , ,
 ,6, ,2, ,3, ,5, ,
 , ,6, ,2, ,5, , ,
 , , ,6, ,5, , , ,
 , ,8, ,1, ,7, , ,
 ,8, ,9, ,4, ,7, ,
 , ,9, , , ,4, , ,
 , , , , , , , , 
'''
solution = '''
3x3;
9,5,2,8,4,1,6,3,7,
1,3,7,5,9,6,2,8,4,
8,6,4,2,7,3,9,5,1,
3,9,6,4,2,7,5,1,8,
7,4,1,6,8,5,3,9,2,
5,2,8,3,1,9,7,4,6,
2,8,5,9,6,4,1,7,3,
6,1,9,7,3,8,4,2,5,
4,7,3,1,5,2,8,6,9
'''

[[tasks]]

puzzle = '''
3x3;
5, , , , , , , , ,
 ,2, , ,6, , ,3, ,
 , ,9, , , , , , ,
 , , ,2, , , , , ,
 , , , ,1,5,3,7,9,
 , , ,8, , , , , ,
 , ,7, , , , , , ,
 ,5, , ,3, , ,1, ,
4, , , , , , , , 
'''
solution = '''
3x3;
5,7,1,3,8,4,9,6,2,
8,2,4,9,6,1,5,3,7,
3,6,9,5,2,7,1,8,4,
6,9,5,2,7,3,8,4,1,
2,4,8,6,1,5,3,7,9,
7,1,3,8,4,9,6,2,5,
1,3,7,4,9,6,2,5,8,
9,5,2,7,3,8,4,1,6,
4,8,6,1,5,2,7,9,3
'''

[[tasks]]

puzzle = '''
3x3;
1, ,5, ,7, , , , ,
 ,3, ,6, , , , , ,
4, ,2, , , , , , ,
 ,4, , , , , , , ,
2, , , , , , , ,5,
 , , , , , , ,3, ,
 , , , , , ,5, ,6,
 , , , , ,6, ,7, ,
 , , , ,5, ,9, ,8
'''
solution = '''
3x3;
1,8,5,3,7,9,6,2,4,
7,3,9,6,4,2,8,5,1,
4,6,2,8,1,5,3,9,7,
9,4,8,5,3,7,1,6,2,
2,7,3,9,6,1,4,8,5,
5,1,6,2,8,4,7,3,9,
3,9,4,7,2,8,5,1,6,
8,5,1,4,9,6,2,7,3,
6,2,7,1,5,3,9,4,8
'''

[[tasks]]

puzzle = '''
3x3;
 , , , , , , , ,6,
 ,4, , , , , , ,1,
 , , , , , , , ,3,
 , , , , ,4,9,1,5,
 , , , , ,8, , , ,
 , , , , ,3, , , ,
 , ,7,3,1,5, , , ,
 , ,2, , , , , , ,
1,8,4, , , , , , 
'''
solution = '''
3x3;
2,7,3,5,9,1,4,8,6,
8,4,9,7,3,6,2,5,1,
5,1,6,4,8,2,7,9,3,
7,3,8,6,2,4,9,1,5,
4,6,1,9,5,8,3,7,2,
9,2,5,1,7,3,6,4,8,
6,9,7,3,1,5,8,2,4,
3,5,2,8,4,7,1,6,9,
1,8,4,2,6,9,5,3,7
'''

[[tasks]]

puzzle = '''
3x3;
 , , , , , , , , ,
 , , , ,4, , , , ,
 , ,7, ,6, ,5, , ,
 , , , ,1, , , , ,
 ,9,4,8, ,5,2,6, ,
 , , , ,9, , , , ,
 , ,1, ,2, ,4, , ,
 , , , ,8, , , , ,
 , , , , , , , , 
'''
solution = '''
3x3;
2,4,9,5,7,3,8,1,6,
6,1,5,2,4,8,3,7,9,
8,3,7,9,6,1,5,2,4,
3,5,2,6,1,7,9,4,8,
7,9,4,8,3,5,2,6,1,
1,6,8,4,9,2,7,3,5,
5,8,1,7,2,6,4,9,3,
9,2,6,3,8,4,1,5,7,
4,7,3,1,5,9,6,8,2
'''
