[[tasks]]

puzzle = '''
3x3;
 , , , , , , , , ,
 , ,1,2, , , ,5,4,
 ,3,4, , , , , ,6,
 , , , ,4, , , ,3,
 , , ,5,7, , , , ,
8, , ,6, , , , , ,
6,8, , , , , , , ,
5, , , , ,8,1, , ,
 , , , , ,9,3, , 
'''
solution = '''
3x3;
2,5,8,4,1,6,9,3,7,
9,6,1,2,3,7,8,5,4,
7,3,4,9,8,5,2,1,6,
1,9,5,8,4,2,6,7,3,
3,2,6,5,7,1,4,8,9,
8,4,7,6,9,3,5,2,1,
6,8,3,1,2,4,7,9,5,
5,7,9,3,6,8,1,4,2,
4,1,2,7,5,9,3,6,8
'''

[[tasks]]

puzzle = '''
3x3;
 , , , , , ,5,6,3,
 ,1,2,3, , , ,7, ,
 , , ,4, , , ,8, ,
1, , ,5, , , , , ,
4,3, , , , , , , ,
5, , , , ,7,1, , ,
7, ,1, , , ,6,9, ,
 , ,8,2, , ,4, , ,
 , , ,6,4, , , , 
'''
solution = '''
3x3;
8,9,4,7,1,2,5,6,3,
6,1,2,3,8,5,9,7,4,
3,7,5,4,9,6,2,8,1,
1,8,7,5,6,4,3,2,9,
4,3,9,1,2,8,7,5,6,
5,2,6,9,3,7,1,4,8,
7,4,1,8,5,3,6,9,2,
9,6,8,2,7,1,4,3,5,
2,5,3,6,4,9,8,1,7
'''

[[tasks]]

puzzle = '''
3x3;
 , , , , ,7,3, , ,
 ,1,2, , , ,5,4, ,
 , ,3,4, , , ,1, ,
 , ,5,6, , , ,8, ,
 , , , , , , , , ,
7, , , , ,2,4, , ,
6,4,1, , , ,8, , ,
5,3, , , ,6,7, , ,
 , , , , ,9, , , 
'''
solution = '''
3x3;
4,5,6,2,1,7,3,9,8,
8,1,2,9,6,3,5,4,7,
9,7,3,4,5,8,6,1,2,
1,2,5,6,7,4,9,8,3,
3,6,4,8,9,1,2,7,5,
7,9,8,5,3,2,4,6,1,
6,4,1,7,2,5,8,3,9,
5,3,9,1,8,6,7,2,4,
2,8,7,3,4,9,1,5,6
'''

[[tasks]]

puzzle = '''
3x3;
 , ,2, , , , ,4, ,
 ,6, ,8, , , , ,2,
8, ,9, ,6, , , , ,
 ,4, ,2, , , , , ,
 , ,6, , , ,5, , ,
 , , , , ,3, ,1, ,
 , , , ,7, ,8, ,5,
1, , , , ,5, ,7, ,
 ,3, , , , ,1, , 
'''
solution = '''
3x3;
7,1,2,5,3,9,6,4,8,
4,6,3,8,1,7,9,5,2,
8,5,9,4,6,2,7,3,1,
9,4,1,2,5,6,3,8,7,
3,7,6,1,8,4,5,2,9,
2,8,5,7,9,3,4,1,6,
6,2,4,3,7,1,8,9,5,
1,9,8,6,4,5,2,7,3,
5,3,7,9,2,8,1,6,4
'''

[[tasks]]

puzzle = '''
3x3;
 , ,2, , , , , , ,
 ,5, ,3, , , ,7, ,
 , ,4, , , ,6, ,8,
 , , , ,2, , ,5, ,
 , , ,6,4,8, , , ,
 ,8, , ,9, , , , ,
6, ,8, , , ,2, , ,
 ,7, , , ,5, ,9, ,
 , , , , , ,4, , 
'''
solution = '''
3x3;
9,6,2,8,1,7,5,4,3,
8,5,1,3,6,4,9,7,2,
7,3,4,9,5,2,6,1,8,
1,4,6,7,2,3,8,5,9,
3,9,5,6,4,8,7,2,1,
2,8,7,5,9,1,3,6,4,
6,1,8,4,7,9,2,3,5,
4,7,3,2,8,5,1,9,6,
5,2,9,1,3,6,4,8,7
'''
