[[tasks]]

puzzle = '''
3x3;
 , ,2, ,9, , , , ,
 , , , , , , , ,6,
 ,3,6,5, , ,7, , ,
 ,2, , , ,9, ,8, ,
 ,5,8,7, , , ,3, ,
 ,6, , , , ,4, , ,
 ,7, , , ,3,5,1, ,
 , , , , , , , , ,
 , , , ,5, , ,4, 
'''
solution = '''
3x3;
7,4,2,3,9,6,8,5,1,
8,1,5,2,4,7,3,9,6,
9,3,6,5,8,1,7,2,4,
4,2,7,6,3,9,1,8,5,
1,5,8,7,2,4,6,3,9,
3,6,9,8,1,5,4,7,2,
2,7,4,9,6,3,5,1,8,
5,8,1,4,7,2,9,6,3,
6,9,3,1,5,8,2,4,7
'''

[[tasks]]

puzzle = '''
3x3;
 , , , ,1, ,4,9,6,
 , ,2, , , , ,3,1,
 , , , , , , , ,2,
 ,3, , , , ,6, , ,
 , , , ,5, , , , ,
 , ,4, , , , ,7, ,
8, , , , , , , , ,
2,1, , , , ,8, , ,
6,7,3, ,9, , , , 
'''
solution = '''
3x3;
3,8,7,5,1,2,4,9,6,
4,6,2,9,8,7,5,3,1,
9,5,1,4,3,6,7,8,2,
7,3,8,1,4,9,6,2,5,
1,2,6,7,5,8,9,4,3,
5,9,4,6,2,3,1,7,8,
8,4,9,2,6,1,3,5,7,
2,1,5,3,7,4,8,6,9,
6,7,3,8,9,5,2,1,4
'''

[[tasks]]

puzzle = '''
3x3;
 , , , , , , , , ,
 ,2,8,7,9, , , , ,
 ,9, , ,6, , , , ,
 ,7, , ,1, , , , ,
 ,1,2,3,4,5,6,7, ,
 , , , ,7, , ,8, ,
 , , , ,8, , ,2, ,
 , , , ,2,6,5,3, ,
 , , , , , , , , 
'''
solution = '''
3x3;
1,6,3,8,5,2,7,9,4,
5,2,8,7,9,4,1,6,3,
4,9,7,1,6,3,8,5,2,
6,7,9,2,1,8,3,4,5,
8,1,2,3,4,5,6,7,9,
3,4,5,6,7,9,2,8,1,
7,3,4,5,8,1,9,2,6,
9,8,1,4,2,6,5,3,7,
2,5,6,9,3,7,4,1,8
'''

[[tasks]]

puzzle = '''
3x3;
5,3, , , , , ,8,7,
1, , , , , , , ,9,
 , , ,7, ,2, , , ,
 , , , , ,4,7, , ,
 , , , , , , , , ,
 , ,4,6, , , , , ,
 , , ,3, ,8, , , ,
7, , , , , , , ,2,
9,4, , , , , ,3,5
'''
solution = '''
3x3;
5,3,2,4,9,1,6,8,7,
1,8,7,5,3,6,2,4,9,
4,9,6,7,8,2,5,1,3,
3,6,9,8,2,4,7,5,1,
8,7,5,9,1,3,4,2,6,
2,1,4,6,7,5,3,9,8,
6,2,1,3,5,8,9,7,4,
7,5,3,1,4,9,8,6,2,
9,4,8,2,6,7,1,3,5
'''

[[tasks]]

puzzle = '''
3x3;
3,6, , , , , , , ,
1,2,4, , , , , , ,
 ,7,8, , , , , , ,
 , , , , , ,2,8, ,
 , , , , , ,6,9,5,
 , , , , , , ,1,7,
 , , ,6,3, , , , ,
 , , ,8,4,7, , , ,
 , , , ,2,1, , , 
'''
solution = '''
3x3;
3,6,9,4,1,2,5,7,8,
1,2,4,5,7,8,3,6,9,
5,7,8,3,6,9,1,2,4,
4,5,7,1,9,6,2,8,3,
2,3,1,7,8,4,6,9,5,
9,8,6,2,5,3,4,1,7,
7,9,2,6,3,5,8,4,1,
6,1,5,8,4,7,9,3,2,
8,4,3,9,2,1,7,5,6
'''
